#!/bin/bash

test_gofmt() {
    hash gofmt 2>&- || { return 0; }
    IFS='
'
    for file in `git diff --cached --name-only --diff-filter=ACM | grep '\.go$'`
    do
        output=`git cat-file -p :${file} | gofmt -l 2>&1`
        if test $? -ne 0
        then
            output=`echo "$output" | sed "s,<standard input>,$file,"`
            syntaxerrors="${list}${output}\n"
        elif test -n "$output"
        then
            list="${list}${file}\n"
        fi
    done
    exit_code=0
    if test -n "$syntaxerrors"
    then
        echo >&2 "gofmt found syntax errors:"
        printf "$syntaxerrors"
        exit_code=1
    fi
    if test -n "$list"
    then
        echo >&2 "gofmt needs to format these files (run gofmt -w and git add):"
        printf "$list"
        exit_code=1
    fi
    if test 0 -eq ${exit_code}
    then
        exit ${exit_code}
    fi
    return 0
}

case "$1" in
    --about|--help|-h )
        echo "Git hook run before committing that checks:"
        echo " - Go code formatting (to disable use the key 'hook.gofmt.disabled' in your git configuration)"
        echo ""
        echo "To disable all hooks add the key 'hook.disabled' in your git configuration."
        ;;
    * )
        if ! ((`git config hook.disabled`)); then
            if ! ((`git config hook.gofmt.disabled`)); then
                test_gofmt
            fi
        fi
        ;;
esac
